/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.JetsonOnWheels
{
    public class ClockSyncResponse : Message
    {
        public const string RosMessageName = "jetson_on_wheels/ClockSync";

        // response field
        public double now { get; set; }
        public double delay { get; set; }
        public double sync_error { get; set; }

        public ClockSyncResponse()
        {
            this.now = 0.0f;
            this.delay = 0.0f;
            this.sync_error = 0.0f;
        }

        public ClockSyncResponse(double now, double delay, double sync_error)
        {
            this.now = now;
            this.delay = delay;
            this.sync_error = sync_error;
        }
    }
}
