/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.JetsonOnWheels
{
    public class ClockSyncRequest : Message
    {
        public const string RosMessageName = "jetson_on_wheels/ClockSync";

        // request field
        public double previous_clock { get; set; }
        public double predicted_clock { get; set; }

        public ClockSyncRequest()
        {
            this.previous_clock = 0.0f;
            this.predicted_clock = 0.0f;
        }

        public ClockSyncRequest(double previous_clock, double predicted_clock)
        {
            this.previous_clock = previous_clock;
            this.predicted_clock = predicted_clock;
        }
    }
}
